/*
try {
    funcaoInexistente();
} catch (e) {
    console.log("Erro:", e);
    console.error("Erro:", e)
}
*/